language: java
#dist: trusty
#script: "mvn cobertura:cobertura"
cache:
  directories:
  - $HOME/.m2
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE misCursosUNQ;'
install:
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
after_success:
  - bash <(curl -s https://codecov.io/bash)
