USE misCursosUNQ;

CREATE TABLE USUARIO (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
dni VARCHAR(20) NOT NULL,
email VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
) engine=innodb default charset=UTF8MB4 collate=UTF8MB4_spanish_ci;

CREATE TABLE MATERIA (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
) engine=innodb default charset=UTF8MB4 collate=UTF8MB4_spanish_ci;

CREATE TABLE COORDINADOR_MATERIA (
USUARIO_id INTEGER UNSIGNED NOT NULL,
MATERIA_id INTEGER UNSIGNED NOT NULL,
PRIMARY KEY(USUARIO_id, MATERIA_id),
CONSTRAINT FK_COORDINADOR FOREIGN KEY(USUARIO_id) REFERENCES USUARIO(id),
CONSTRAINT FK_MATERIA FOREIGN KEY(MATERIA_id) REFERENCES MATERIA(id)
)engine=innodb default charset=UTF8MB4 collate=UTF8MB4_spanish_ci;

CREATE TABLE DOCENTE_CURSADA (
USUARIO_id INTEGER UNSIGNED NOT NULL,
CURSADA_id INTEGER UNSIGNED NOT NULL,
PRIMARY KEY(USUARIO_id, CURSADA_id),
CONSTRAINT FK_DOCENTE FOREIGN KEY(USUARIO_id) REFERENCES USUARIO(id),
CONSTRAINT FK_CURSADA FOREIGN KEY(CURSADA_id) REFERENCES CURSADA(id)
)engine=innodb default charset=UTF8MB4 collate=UTF8MB4_spanish_ci;